title: Jordan's Blog
#author:
#  name: GitHub User
#  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Copyright © 2023 — Jordan Conner


show_excerpts: true # set to true to show excerpts on the homepage


# Regular minima theme provided by GitHub Pages via theme: minima does not contain support for skin: dark
# Use remote_theme to grab latest GitHub pages supported minima (v2.5.1) which does support skin: dark
# https://github.com/jekyll/minima/tree/3cdd14dff1216f561c68329e0b7420c2dc9b796a
remote_theme: jekyll/minima@3cdd14d
minima:
  skin: dark



# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
